drop table solicitud_seguimiento;
drop table solicitud;
drop table documento;
drop table empleado;
drop table empresa;
drop table persona;
drop table rol;
drop table area;
drop table anexo;
drop table distrito;
drop table tipo_documento_requisito;
drop table tipo_documento_consideracion;
drop table tipo_documento;
drop table grupo;
drop table consideracion;
drop table requisito;

create table consideracion (
  id bigint generated by default as identity primary key,
  fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
  fecha_edicion timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre varchar not null,
  descripcion varchar not null
);

create table requisito (
  id bigint generated by default as identity primary key,
  fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
  fecha_edicion timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre varchar not null,
  descripcion varchar not null,
  url_imagen varchar null
);

create table rol (
  id bigint generated by default as identity primary key,
  fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
  fecha_edicion timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre varchar not null,
  descripcion varchar  null
);

create table area(
  id bigint generated by default as identity primary key,
  fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
  fecha_edicion timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre varchar not null,
  descripcion varchar null
);

create table distrito (
  id bigint generated by default as identity primary key,
  fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
  fecha_edicion timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre varchar not null,
  descripcion varchar null  
);

create table anexo (
  id bigint generated by default as identity primary key,
  fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
  fecha_edicion timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre varchar not null,
  descripcion varchar  null,
  id_distrito bigint not null references distrito 
);

create table grupo (
  id bigint generated by default as identity primary key,
  fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
  fecha_edicion timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre varchar not null,
  descripcion varchar  null
);

create table tipo_documento (
  id bigint generated by default as identity primary key,
  fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
  fecha_edicion timestamp with time zone default timezone('utc'::text, now()) not null,
  codigo varchar not  null,
  nombre varchar not null,
  descripcion varchar null,
  tiempo_entrega int null,
  costo decimal not null,
  id_grupo bigint not null references grupo
);

create table tipo_documento_requisito (
  id bigint generated by default as identity primary key,
  fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
  fecha_edicion timestamp with time zone default timezone('utc'::text, now()) not null,
  id_tipo_documento bigint not null references tipo_documento,
  id_requisito bigint not null references requisito
);

create table tipo_documento_consideracion (
  id bigint generated by default as identity primary key,
  fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
  fecha_edicion timestamp with time zone default timezone('utc'::text, now()) not null,
  id_tipo_documento bigint not null references tipo_documento,
  id_consideracion bigint not null references consideracion
);

create table empleado (
  id bigint generated by default as identity primary key,
  fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
  fecha_edicion timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre varchar not null,
  apellido varchar not null,
  numero_documento varchar not null,
  fecha_nacimiento timestamp not null,
  sexo varchar not null,
  direccion varchar not null,
  celular varchar null,
  email varchar null,
  tipo_contrato varchar not null,
  estado bool not null,
  url_imagen varchar null,
  id_distrito bigint not null references distrito, 
  id_area bigint not null references area, 
  id_rol bigint not null references rol
);

create table empresa (
  id bigint generated by default as identity primary key,
  fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
  fecha_edicion timestamp with time zone default timezone('utc'::text, now()) not null,
  numero_ruc varchar not null,
  razon_social varchar not null,
  direccion varchar not null,
  celular varchar null,
  email varchar null,
  estado bool not null,
  id_distrito bigint not null references distrito,
  id_anexo bigint null references anexo
);

create table persona (
  id bigint generated by default as identity primary key,
  fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
  fecha_edicion timestamp with time zone default timezone('utc'::text, now()) not null,
  tipo_documento varchar not null,
  numero_documento varchar not null,
  nombre varchar not null,
  apellido varchar not null,  
  fecha_nacimiento timestamp null,
  sexo varchar not null,
  direccion varchar not null,
  celular varchar null,
  email varchar null,
  estado bool not null,
  id_distrito bigint not null references distrito,
  id_anexo bigint null references anexo
);

create table documento (
  id bigint generated by default as identity primary key,
  fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
  fecha_edicion timestamp with time zone default timezone('utc'::text, now()) not null,
  -- persona, empresa
  tipo_entidad varchar not null,
  numero_documento varchar not null,
  observacion varchar not null,
  fecha_documento timestamp not null,
  url_archivo varchar null,
  es_anulado bool not null,
  fecha_anulacion timestamp null,
  motivo_anulacion varchar null,
  id_empleado bigint not null references empleado,
  id_empresa bigint null references empresa,
  id_persona bigint null references persona,
  id_tipo_documento bigint not null references tipo_documento
);

create table solicitud (
  id bigint generated by default as identity primary key,
  fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
  fecha_edicion timestamp with time zone default timezone('utc'::text, now()) not null,
  asunto varchar not null,
  numero_documento varchar not null,
  fecha_inicio timestamp not null,
  fecha_plazo timestamp null,
  motivo varchar not null,
  -- persona, empresa
  tipo_entidad varchar not null,
  i_total decimal(13,2) not null default 0
  id_tipo_documento bigint not null references tipo_documento,
  id_documento bigint not null references documento,
  id_area bigint not null references area,
  id_empleado bigint not null references empleado,
  id_persona bigint not null references persona,
  id_empresa bigint null references empresa
);

create table solicitud_seguimiento (
  id bigint generated by default as identity primary key,
  fecha_creacion timestamp with time zone default timezone('utc'::text, now()) not null,
  fecha_edicion timestamp with time zone default timezone('utc'::text, now()) not null,
  fecha timestamp not null,
  estado varchar not null,
  observaciones varchar not null,
  id_solicitud bigint not null references solicitud,
  id_empleado bigint not null references empleado,
  id_area bigint not null references area
);